### ISSUE TITLE
panic: Not find Event Lookup , please check metadata info - empty lookup for block 10156936 (Polkadot)

### ISSUE THREAD

**Issue by UnicornIdeas** [itering/scale.go#57]
Hello,
I am trying to decode all events from Polkadot and it all went perfect until block 10156936 where the decoder threw me the error:

`panic: Not find Event Lookup , please check metadata info`

I think it is an error with the decoding, maybe the Type was not extracted correctly, the elementCount is correct, there are 24 events on that block.

I saved all the info that the decoder managed to extract before panic:

```
EventsDecoder Process function elementCount: 24
e.Phase: 0
e.ExtrinsicIdx: 0
e: 0000 [] {  [] [] []} []
e.Type: 0000
e.Event: { ExtrinsicSuccess [An extrinsic completed successfully.] [frame_support:weights:DispatchInfo@19] [DispatchInfo]}
e.Module: System
e.Phase: 0
e.ExtrinsicIdx: 1
e: 3501 [] { ExtrinsicSuccess [An extrinsic completed successfully.] [frame_support:weights:DispatchInfo@19] [DispatchInfo]} []
e.Type: 3501
e.Event: { CandidateIncluded [A candidate was included. `[candidate, head_data]`] [polkadot_primitives:v2:CandidateReceipt Vec<U8> U32 U32] [CandidateReceipt<Hash> HeadData CoreIndex GroupIndex]}
e.Module: ParaInclusion
e.Phase: 0
e.ExtrinsicIdx: 1
e: 3501 [] { CandidateIncluded [A candidate was included. `[candidate, head_data]`] [polkadot_primitives:v2:CandidateReceipt Vec<U8> U32 U32] [CandidateReceipt<Hash> HeadData CoreIndex GroupIndex]} []
e.Type: 3501
e.Event: { CandidateIncluded [A candidate was included. `[candidate, head_data]`] [polkadot_primitives:v2:CandidateReceipt Vec<U8> U32 U32] [CandidateReceipt<Hash> HeadData CoreIndex GroupIndex]}
e.Module: ParaInclusion
e.Phase: 0
e.ExtrinsicIdx: 1
e: 3501 [] { CandidateIncluded [A candidate was included. `[candidate, head_data]`] [polkadot_primitives:v2:CandidateReceipt Vec<U8> U32 U32] [CandidateReceipt<Hash> HeadData CoreIndex GroupIndex]} []
e.Type: 3501
e.Event: { CandidateIncluded [A candidate was included. `[candidate, head_data]`] [polkadot_primitives:v2:CandidateReceipt Vec<U8> U32 U32] [CandidateReceipt<Hash> HeadData CoreIndex GroupIndex]}
e.Module: ParaInclusion
e.Phase: 0
e.ExtrinsicIdx: 1
e: 3501 [] { CandidateIncluded [A candidate was included. `[candidate, head_data]`] [polkadot_primitives:v2:CandidateReceipt Vec<U8> U32 U32] [CandidateReceipt<Hash> HeadData CoreIndex GroupIndex]} []
e.Type: 3501
e.Event: { CandidateIncluded [A candidate was included. `[candidate, head_data]`] [polkadot_primitives:v2:CandidateReceipt Vec<U8> U32 U32] [CandidateReceipt<Hash> HeadData CoreIndex GroupIndex]}
e.Module: ParaInclusion
e.Phase: 0
e.ExtrinsicIdx: 1
e: 3501 [] { CandidateIncluded [A candidate was included. `[candidate, head_data]`] [polkadot_primitives:v2:CandidateReceipt Vec<U8> U32 U32] [CandidateReceipt<Hash> HeadData CoreIndex GroupIndex]} []
e.Type: 3501
e.Event: { CandidateIncluded [A candidate was included. `[candidate, head_data]`] [polkadot_primitives:v2:CandidateReceipt Vec<U8> U32 U32] [CandidateReceipt<Hash> HeadData CoreIndex GroupIndex]}
e.Module: ParaInclusion
e.Phase: 0
e.ExtrinsicIdx: 1
e: 3501 [] { CandidateIncluded [A candidate was included. `[candidate, head_data]`] [polkadot_primitives:v2:CandidateReceipt Vec<U8> U32 U32] [CandidateReceipt<Hash> HeadData CoreIndex GroupIndex]} []
e.Type: 3501
e.Event: { CandidateIncluded [A candidate was included. `[candidate, head_data]`] [polkadot_primitives:v2:CandidateReceipt Vec<U8> U32 U32] [CandidateReceipt<Hash> HeadData CoreIndex GroupIndex]}
e.Module: ParaInclusion
e.Phase: 0
e.ExtrinsicIdx: 1
e: 3501 [] { CandidateIncluded [A candidate was included. `[candidate, head_data]`] [polkadot_primitives:v2:CandidateReceipt Vec<U8> U32 U32] [CandidateReceipt<Hash> HeadData CoreIndex GroupIndex]} []
e.Type: 3501
e.Event: { CandidateIncluded [A candidate was included. `[candidate, head_data]`] [polkadot_primitives:v2:CandidateReceipt Vec<U8> U32 U32] [CandidateReceipt<Hash> HeadData CoreIndex GroupIndex]}
e.Module: ParaInclusion
e.Phase: 0
e.ExtrinsicIdx: 1
e: 3501 [] { CandidateIncluded [A candidate was included. `[candidate, head_data]`] [polkadot_primitives:v2:CandidateReceipt Vec<U8> U32 U32] [CandidateReceipt<Hash> HeadData CoreIndex GroupIndex]} []
e.Type: 3501
e.Event: { CandidateIncluded [A candidate was included. `[candidate, head_data]`] [polkadot_primitives:v2:CandidateReceipt Vec<U8> U32 U32] [CandidateReceipt<Hash> HeadData CoreIndex GroupIndex]}
e.Module: ParaInclusion
e.Phase: 0
e.ExtrinsicIdx: 1
e: 3500 [] { CandidateIncluded [A candidate was included. `[candidate, head_data]`] [polkadot_primitives:v2:CandidateReceipt Vec<U8> U32 U32] [CandidateReceipt<Hash> HeadData CoreIndex GroupIndex]} []
e.Type: 3500
e.Event: { CandidateBacked [A candidate was backed. `[candidate, head_data]`] [polkadot_primitives:v2:CandidateReceipt Vec<U8> U32 U32] [CandidateReceipt<Hash> HeadData CoreIndex GroupIndex]}
e.Module: ParaInclusion
e.Phase: 0
e.ExtrinsicIdx: 1
e: 3500 [] { CandidateBacked [A candidate was backed. `[candidate, head_data]`] [polkadot_primitives:v2:CandidateReceipt Vec<U8> U32 U32] [CandidateReceipt<Hash> HeadData CoreIndex GroupIndex]} []
e.Type: 3500
e.Event: { CandidateBacked [A candidate was backed. `[candidate, head_data]`] [polkadot_primitives:v2:CandidateReceipt Vec<U8> U32 U32] [CandidateReceipt<Hash> HeadData CoreIndex GroupIndex]}
e.Module: ParaInclusion
e.Phase: 0
e.ExtrinsicIdx: 1
e: 3500 [] { CandidateBacked [A candidate was backed. `[candidate, head_data]`] [polkadot_primitives:v2:CandidateReceipt Vec<U8> U32 U32] [CandidateReceipt<Hash> HeadData CoreIndex GroupIndex]} []
e.Type: 3500
e.Event: { CandidateBacked [A candidate was backed. `[candidate, head_data]`] [polkadot_primitives:v2:CandidateReceipt Vec<U8> U32 U32] [CandidateReceipt<Hash> HeadData CoreIndex GroupIndex]}
e.Module: ParaInclusion
e.Phase: 0
e.ExtrinsicIdx: 1
e: 0000 [] { CandidateBacked [A candidate was backed. `[candidate, head_data]`] [polkadot_primitives:v2:CandidateReceipt Vec<U8> U32 U32] [CandidateReceipt<Hash> HeadData CoreIndex GroupIndex]} []
e.Type: 0000
e.Event: { ExtrinsicSuccess [An extrinsic completed successfully.] [frame_support:weights:DispatchInfo@19] [DispatchInfo]}
e.Module: System
e.Phase: 0
e.ExtrinsicIdx: 2
e: 0508 [] { ExtrinsicSuccess [An extrinsic completed successfully.] [frame_support:weights:DispatchInfo@19] [DispatchInfo]} []
e.Type: 0508
e.Event: { Withdraw [Some amount was withdrawn from the account (e.g. for transaction fees).] [[U8; 32] U128] [AccountId Balance]}
e.Module: Balances
e.Phase: 0
e.ExtrinsicIdx: 2
e: 0507 [] { Withdraw [Some amount was withdrawn from the account (e.g. for transaction fees).] [[U8; 32] U128] [AccountId Balance]} []
e.Type: 0507
e.Event: { Deposit [Some amount was deposited (e.g. for transaction fees).] [[U8; 32] U128] [AccountId Balance]}
e.Module: Balances
e.Phase: 0
e.ExtrinsicIdx: 2
e: 1306 [] { Deposit [Some amount was deposited (e.g. for transaction fees).] [[U8; 32] U128] [AccountId Balance]} []
e.Type: 1306
e.Event: { Deposit [Some funds have been deposited.] [U128] [BalanceOf]}
e.Module: Treasury
e.Phase: 0
e.ExtrinsicIdx: 2
e: 0507 [] { Deposit [Some funds have been deposited.] [U128] [BalanceOf]} []
e.Type: 0507
e.Event: { Deposit [Some amount was deposited (e.g. for transaction fees).] [[U8; 32] U128] [AccountId Balance]}
e.Module: Balances
e.Phase: 0
e.ExtrinsicIdx: 2
e: 0001 [] { Deposit [Some amount was deposited (e.g. for transaction fees).] [[U8; 32] U128] [AccountId Balance]} []
e.Type: 0001
e.Event: { ExtrinsicFailed [An extrinsic failed.] [sp_runtime:DispatchError@22 frame_support:weights:DispatchInfo@19] [DispatchError DispatchInfo]}
e.Module: System
e.Phase: 0
e.ExtrinsicIdx: 50331648
e: 0000 [] { ExtrinsicFailed [An extrinsic failed.] [sp_runtime:DispatchError@22 frame_support:weights:DispatchInfo@19] [DispatchError DispatchInfo]} []
e.Type: 0000
e.Event: { ExtrinsicSuccess [An extrinsic completed successfully.] [frame_support:weights:DispatchInfo@19] [DispatchInfo]}
e.Module: System
e.Phase: 0
e.ExtrinsicIdx: 0
e:  [] { ExtrinsicSuccess [An extrinsic completed successfully.] [frame_support:weights:DispatchInfo@19] [DispatchInfo]} []
e.Type: 
panic: Not find Event Lookup , please check metadata info

goroutine 314 [running]:
github.com/itering/scale%2ego.(*EventRecord).Process(0xc008f999a8)
        /tmp/scale.go/event.go:81 +0xe99
github.com/itering/scale%2ego.(*EventsDecoder).Process(0xc008f99f18)
        /tmp/scale.go/event.go:38 +0x19a
```

I hope you can help me with this issue

**Comment by UnicornIdeas** [comment]
If I skip that block, the next one throwing a panic is 10157009 with the following data:

```
EventsDecoder Process function elementCount: 33
e.Phase: 0
e.ExtrinsicIdx: 0
e: 0000 [] {  [] [] []} []
e.Type: 0000
e.Event: { ExtrinsicSuccess [An extrinsic completed successfully.] [frame_support:weights:DispatchInfo@19] [DispatchInfo]}
e.Module: System
e.Phase: 0
e.ExtrinsicIdx: 1
e: 3501 [] { ExtrinsicSuccess [An extrinsic completed successfully.] [frame_support:weights:DispatchInfo@19] [DispatchInfo]} []
e.Type: 3501
e.Event: { CandidateIncluded [A candidate was included. `[candidate, head_data]`] [polkadot_primitives:v2:CandidateReceipt Vec<U8> U32 U32] [CandidateReceipt<Hash> HeadData CoreIndex GroupIndex]}
e.Module: ParaInclusion
e.Phase: 0
e.ExtrinsicIdx: 1
e: 3501 [] { CandidateIncluded [A candidate was included. `[candidate, head_data]`] [polkadot_primitives:v2:CandidateReceipt Vec<U8> U32 U32] [CandidateReceipt<Hash> HeadData CoreIndex GroupIndex]} []
e.Type: 3501
e.Event: { CandidateIncluded [A candidate was included. `[candidate, head_data]`] [polkadot_primitives:v2:CandidateReceipt Vec<U8> U32 U32] [CandidateReceipt<Hash> HeadData CoreIndex GroupIndex]}
e.Module: ParaInclusion
e.Phase: 0
e.ExtrinsicIdx: 1
e: 3501 [] { CandidateIncluded [A candidate was included. `[candidate, head_data]`] [polkadot_primitives:v2:CandidateReceipt Vec<U8> U32 U32] [CandidateReceipt<Hash> HeadData CoreIndex GroupIndex]} []
e.Type: 3501
e.Event: { CandidateIncluded [A candidate was included. `[candidate, head_data]`] [polkadot_primitives:v2:CandidateReceipt Vec<U8> U32 U32] [CandidateReceipt<Hash> HeadData CoreIndex GroupIndex]}
e.Module: ParaInclusion
e.Phase: 0
e.ExtrinsicIdx: 1
e: 3501 [] { CandidateIncluded [A candidate was included. `[candidate, head_data]`] [polkadot_primitives:v2:CandidateReceipt Vec<U8> U32 U32] [CandidateReceipt<Hash> HeadData CoreIndex GroupIndex]} []
e.Type: 3501
e.Event: { CandidateIncluded [A candidate was included. `[candidate, head_data]`] [polkadot_primitives:v2:CandidateReceipt Vec<U8> U32 U32] [CandidateReceipt<Hash> HeadData CoreIndex GroupIndex]}
e.Module: ParaInclusion
e.Phase: 0
e.ExtrinsicIdx: 1
e: 3501 [] { CandidateIncluded [A candidate was included. `[candidate, head_data]`] [polkadot_primitives:v2:CandidateReceipt Vec<U8> U32 U32] [CandidateReceipt<Hash> HeadData CoreIndex GroupIndex]} []
e.Type: 3501
e.Event: { CandidateIncluded [A candidate was included. `[candidate, head_data]`] [polkadot_primitives:v2:CandidateReceipt Vec<U8> U32 U32] [CandidateReceipt<Hash> HeadData CoreIndex GroupIndex]}
e.Module: ParaInclusion
e.Phase: 0
e.ExtrinsicIdx: 1
e: 3500 [] { CandidateIncluded [A candidate was included. `[candidate, head_data]`] [polkadot_primitives:v2:CandidateReceipt Vec<U8> U32 U32] [CandidateReceipt<Hash> HeadData CoreIndex GroupIndex]} []
e.Type: 3500
e.Event: { CandidateBacked [A candidate was backed. `[candidate, head_data]`] [polkadot_primitives:v2:CandidateReceipt Vec<U8> U32 U32] [CandidateReceipt<Hash> HeadData CoreIndex GroupIndex]}
e.Module: ParaInclusion
e.Phase: 0
e.ExtrinsicIdx: 1
e: 3500 [] { CandidateBacked [A candidate was backed. `[candidate, head_data]`] [polkadot_primitives:v2:CandidateReceipt Vec<U8> U32 U32] [CandidateReceipt<Hash> HeadData CoreIndex GroupIndex]} []
e.Type: 3500
e.Event: { CandidateBacked [A candidate was backed. `[candidate, head_data]`] [polkadot_primitives:v2:CandidateReceipt Vec<U8> U32 U32] [CandidateReceipt<Hash> HeadData CoreIndex GroupIndex]}
e.Module: ParaInclusion
e.Phase: 0
e.ExtrinsicIdx: 1
e: 3500 [] { CandidateBacked [A candidate was backed. `[candidate, head_data]`] [polkadot_primitives:v2:CandidateReceipt Vec<U8> U32 U32] [CandidateReceipt<Hash> HeadData CoreIndex GroupIndex]} []
e.Type: 3500
e.Event: { CandidateBacked [A candidate was backed. `[candidate, head_data]`] [polkadot_primitives:v2:CandidateReceipt Vec<U8> U32 U32] [CandidateReceipt<Hash> HeadData CoreIndex GroupIndex]}
e.Module: ParaInclusion
e.Phase: 0
e.ExtrinsicIdx: 1
e: 3500 [] { CandidateBacked [A candidate was backed. `[candidate, head_data]`] [polkadot_primitives:v2:CandidateReceipt Vec<U8> U32 U32] [CandidateReceipt<Hash> HeadData CoreIndex GroupIndex]} []
e.Type: 3500
e.Event: { CandidateBacked [A candidate was backed. `[candidate, head_data]`] [polkadot_primitives:v2:CandidateReceipt Vec<U8> U32 U32] [CandidateReceipt<Hash> HeadData CoreIndex GroupIndex]}
e.Module: ParaInclusion
e.Phase: 0
e.ExtrinsicIdx: 1
e: 3500 [] { CandidateBacked [A candidate was backed. `[candidate, head_data]`] [polkadot_primitives:v2:CandidateReceipt Vec<U8> U32 U32] [CandidateReceipt<Hash> HeadData CoreIndex GroupIndex]} []
e.Type: 3500
e.Event: { CandidateBacked [A candidate was backed. `[candidate, head_data]`] [polkadot_primitives:v2:CandidateReceipt Vec<U8> U32 U32] [CandidateReceipt<Hash> HeadData CoreIndex GroupIndex]}
e.Module: ParaInclusion
e.Phase: 0
e.ExtrinsicIdx: 1
e: 3500 [] { CandidateBacked [A candidate was backed. `[candidate, head_data]`] [polkadot_primitives:v2:CandidateReceipt Vec<U8> U32 U32] [CandidateReceipt<Hash> HeadData CoreIndex GroupIndex]} []
e.Type: 3500
e.Event: { CandidateBacked [A candidate was backed. `[candidate, head_data]`] [polkadot_primitives:v2:CandidateReceipt Vec<U8> U32 U32] [CandidateReceipt<Hash> HeadData CoreIndex GroupIndex]}
e.Module: ParaInclusion
e.Phase: 0
e.ExtrinsicIdx: 1
e: 3500 [] { CandidateBacked [A candidate was backed. `[candidate, head_data]`] [polkadot_primitives:v2:CandidateReceipt Vec<U8> U32 U32] [CandidateReceipt<Hash> HeadData CoreIndex GroupIndex]} []
e.Type: 3500
e.Event: { CandidateBacked [A candidate was backed. `[candidate, head_data]`] [polkadot_primitives:v2:CandidateReceipt Vec<U8> U32 U32] [CandidateReceipt<Hash> HeadData CoreIndex GroupIndex]}
e.Module: ParaInclusion
e.Phase: 0
e.ExtrinsicIdx: 1
e: 0000 [] { CandidateBacked [A candidate was backed. `[candidate, head_data]`] [polkadot_primitives:v2:CandidateReceipt Vec<U8> U32 U32] [CandidateReceipt<Hash> HeadData CoreIndex GroupIndex]} []
e.Type: 0000
e.Event: { ExtrinsicSuccess [An extrinsic completed successfully.] [frame_support:weights:DispatchInfo@19] [DispatchInfo]}
e.Module: System
e.Phase: 0
e.ExtrinsicIdx: 2
e: 0508 [] { ExtrinsicSuccess [An extrinsic completed successfully.] [frame_support:weights:DispatchInfo@19] [DispatchInfo]} []
e.Type: 0508
e.Event: { Withdraw [Some amount was withdrawn from the account (e.g. for transaction fees).] [[U8; 32] U128] [AccountId Balance]}
e.Module: Balances
e.Phase: 0
e.ExtrinsicIdx: 2
e: 0507 [] { Withdraw [Some amount was withdrawn from the account (e.g. for transaction fees).] [[U8; 32] U128] [AccountId Balance]} []
e.Type: 0507
e.Event: { Deposit [Some amount was deposited (e.g. for transaction fees).] [[U8; 32] U128] [AccountId Balance]}
e.Module: Balances
e.Phase: 0
e.ExtrinsicIdx: 2
e: 1306 [] { Deposit [Some amount was deposited (e.g. for transaction fees).] [[U8; 32] U128] [AccountId Balance]} []
e.Type: 1306
e.Event: { Deposit [Some funds have been deposited.] [U128] [BalanceOf]}
e.Module: Treasury
e.Phase: 0
e.ExtrinsicIdx: 2
e: 0507 [] { Deposit [Some funds have been deposited.] [U128] [BalanceOf]} []
e.Type: 0507
e.Event: { Deposit [Some amount was deposited (e.g. for transaction fees).] [[U8; 32] U128] [AccountId Balance]}
e.Module: Balances
e.Phase: 0
e.ExtrinsicIdx: 2
e: 0001 [] { Deposit [Some amount was deposited (e.g. for transaction fees).] [[U8; 32] U128] [AccountId Balance]} []
e.Type: 0001
e.Event: { ExtrinsicFailed [An extrinsic failed.] [sp_runtime:DispatchError@22 frame_support:weights:DispatchInfo@19] [DispatchError DispatchInfo]}
e.Module: System
e.Phase: 0
e.ExtrinsicIdx: 50331648
e: 0000 [] { ExtrinsicFailed [An extrinsic failed.] [sp_runtime:DispatchError@22 frame_support:weights:DispatchInfo@19] [DispatchError DispatchInfo]} []
e.Type: 0000
e.Event: { ExtrinsicSuccess [An extrinsic completed successfully.] [frame_support:weights:DispatchInfo@19] [DispatchInfo]}
e.Module: System
e.Phase: 0
e.ExtrinsicIdx: 0
e:  [] { ExtrinsicSuccess [An extrinsic completed successfully.] [frame_support:weights:DispatchInfo@19] [DispatchInfo]} []
e.Type: 
panic: Not find Event Lookup , please check metadata info
```

**Comment by helmealex** [comment]
```
e.Phase: 0
e.ExtrinsicIdx: 50331648
e: 0000 [] { ExtrinsicFailed [An extrinsic failed.] [sp_runtime:DispatchError@22 frame_support:weights:DispatchInfo@19] [DispatchError DispatchInfo]} []
e.Type: 0000
e.Event: { ExtrinsicSuccess [An extrinsic completed successfully.] [frame_support:weights:DispatchInfo@19] [DispatchInfo]}
e.Module: System
```
The first event with ExtrinsicIdx=3 is wrongly decoded as ExtrinsicIdx=50331648, the sequence of hex octets "03000000" being equal to the decimal value 50331648.

**Comment by helmealex** [comment]
One supposition is that the event structure of the event before the one described above is wrongly formatted. Before the event with extrinsic id `e.ExtrinsicIdx: 50331648`, we have an "ExtrinsicFailed" event which I think interferes with the next event (the trailing 0s of that event are taken into account in the first event of extrinsic id 3, that being the source of the wrongly decoded 50331648).

**Comment by freehere107** [comment]
@helmealex Thanks for your feedback, I will check it

**Comment by freehere107** [comment]
https://gist.github.com/freehere107/c3f074edf684c130ac50fb415f1f93da

@helmealex hi, I wrote a test and didn't encounter this problem. You can look at the code above

**Comment by helmealex** [comment]
@freehere107 I will test it later this day and come back with feedback. Thank you!

**Comment by helmealex** [comment]
The behavior is weird. If run single, the testing function written by you works, but if run in a highly concurrent application, with other decoders initiated and used before, it throws the error mentioned by @UnicornIdeas. Do you know how the decoder behaves if concurrent environments?

**Comment by freehere107** [comment]
@UnicornIdeas hi, This question does not appear on subscan, I will contact you if I find something new
